spring.application.name=truyen247-be

spring.datasource.url=jdbc:mysql://localhost:3306/truyen_247?useSSL=false
spring.datasource.username=root
spring.datasource.password=Tien@27022002

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
# Cau hinh JWT
truyen247.app.jwtSecret=======================truyen247=Spring===========================
truyen247.app.jwtExpirationMs=86400000
# Cau hinh AWS S3
cloud.aws.credentials.accessKey=AKIA2CUNL3GSRRVN2J3R
cloud.aws.credentials.secretKey=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
cloud.aws.region.static=ap-southeast-2
cloud.aws.s3.bucket-name=my-truyen247-springboot
