spring.application.name=truyen247-be

spring.datasource.url=jdbc:mysql://localhost:3306/truyen_247?useSSL=false
spring.datasource.username=root
spring.datasource.password=Tien@27022002

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
# App Properties
truyen247.app.jwtSecret=======================truyen247=Spring===========================
truyen247.app.jwtExpirationMs=86400000
# C?u h�nh Google OAuth2